---
persistence:
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    futures: false
    envVarPrefix: binance
    heikinAshi: false

exchangeStrategies:
 
- on: binance
  drift:
    canvasPath: "./output.png"
    symbol: ETHBUSD
    # kline interval for indicators
    interval: 15m
    window: 2
    stoploss: 0.3%
    source: close
    predictOffset: 2
    # the init value of takeProfitFactor Series, position avg +- takeProfitFactor * atr as take profit price
    takeProfitFactor: 6
    profitFactorWindow: 8
    noTrailingStopLoss: false
    trailingStopLossType: kline
    # stddev on high/low-source
    hlVarianceMultiplier: 0.23
    hlRangeWindow: 5
    smootherWindow: 1
    fisherTransformWindow: 9
    atrWindow: 14
    # orders not been traded will be canceled after `pendingMinutes` minutes
    pendingMinutes: 4
    noRebalance: true
    trendWindow: 12
    rebalanceFilter: 1.5

    trailingActivationRatio: [0.008, 0.015]
    trailingCallbackRate: [0.002, 0.001]

    generateGraph: true
    graphPNLDeductFee: true
    graphPNLPath: "./pnl.png"
    graphCumPNLPath: "./cumpnl.png"
    #exits:
    #- roiStopLoss:
    #   percentage: 0.8%
    #- roiTakeProfit:
    #   percentage: 35%
    #- protectiveStopLoss:
    #   activationRatio: 0.6%
    #   stopLossRatio: 0.1%
    #   placeStopOrder: false
    #- protectiveStopLoss:
    #   activationRatio: 5%
    #   stopLossRatio: 1%
    #   placeStopOrder: false
    #- cumulatedVolumeTakeProfit:
    #   interval: 5m
    #   window: 2
    #   minQuoteVolume: 200_000_000
    #- protectiveStopLoss:
    #    activationRatio: 2%
    #    stopLossRatio: 1%
    #    placeStopOrder: false

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - ETHBUSD

backtest:
  startTime: "2022-01-01"
  endTime: "2022-07-30"
  symbols:
    - ETHBUSD
  sessions: [binance]
  accounts:
    binance:
      makerFeeRate: 0.0000
      #takerFeeRate: 0.00001
      balances:
        ETH: 10
        BUSD: 5000.0
