sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
#    futures: true


exchangeStrategies:
- on: binance
  pivotshort:
    symbol: GMTUSDT
    interval: 5m

    pivotLength:  120

    entry:
      catBounceRatio: 1%
      quantity: 1000
      numLayers: 3
#        marginOrderSideEffect: borrow

    exit:
      takeProfitPercentage: 13%
      stopLossPercentage: 0.5%
      shadowTPRatio: 13%
#        marginOrderSideEffect: repay



backtest:
  sessions:
    - binance
  startTime: "2022-04-01"
  endTime: "2022-06-03"
  symbols:
    - GMTUSDT
  account:
    binance:
      balances:
        GMT: 3_000.0
        USDT: 3_000.0
