# usage:
#
#   go run ./cmd/bbgo optimize --config config/pivotshort-ETHUSDT.yaml  --optimizer-config config/pivotshort_optimizer.yaml --debug
#
---
matrix:

- type: iterate
  label: interval
  path: '/exchangeStrategies/0/pivotshort/interval'
  values: [ "1m", "5m", "30m" ]

#- type: range
#  path: '/exchangeStrategies/0/pivotshort/pivotLength'
#  label: pivotLength
#  min: 100.0
#  max: 200.0
#  step: 20.0

#  - type: range
#    path: '/exchangeStrategies/0/pivotshort/breakLow/stopEMARange'
#    label: stopEMARange
#    min: 0%
#    max: 10%
#    step: 1%

#  - type: range
#    path: '/exchangeStrategies/0/pivotshort/exit/roiStopLossPercentage'
#    label: roiStopLossPercentage
#    min: 0.5%
#    max: 2%
#    step: 0.5%
#  
#  - type: range
#    path: '/exchangeStrategies/0/pivotshort/exit/roiTakeProfitPercentage'
#    label: roiTakeProfitPercentage
#    min: 10%
#    max: 50%
#    step: 5%
#  
#  - type: range
#    path: '/exchangeStrategies/0/pivotshort/exit/roiMinTakeProfitPercentage'
#    label: roiMinTakeProfitPercentage
#    min: 3%
#    max: 10%
#    step: 1%
#  
