---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  # if you want to route channel by symbol
  symbolChannels:
    "^BTC": "btc"
    "^ETH": "eth"
    "^BNB": "bnb"

  # object routing rules
  routing:
    trade: "$symbol"
    order: "$symbol"
    submitOrder: "$session" # not supported yet
    pnL: "bbgo-pnl"

sessions:
  binance_margin_linkusdt:
    exchange: binance
    margin: true
    isolatedMargin: true
    isolatedMarginSymbol: LINKUSDT

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    max:
      orderExecutor:
        bySymbol:
          BTCUSDT:
            basic:
              minQuoteBalance: 100.0
              maxBaseAssetBalance: 3.0
              minBaseAssetBalance: 0.0
              maxOrderAmount: 1000.0

backtest:
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2020-09-04"
  endTime: "2020-09-14"
  symbols:
  - BTCUSDT
  - ETHUSDT
  account:
    makerCommission: 15
    takerCommission: 15
    balances:
      BTC: 0.0
      USDT: 10000.0

exchangeStrategies:

- on: binance_margin_linkusdt
  support:
    symbol: LINKUSDT
    interval: 1m
    minVolume: 1_000
    marginOrderSideEffect: borrow

    scaleQuantity:
      byVolume:
        exp:
          domain: [ 1_000, 200_000 ]
          range: [ 0.5, 1.0 ]

    maxBaseAssetBalance: 1000.0
    minQuoteAssetBalance: 2000.0

    targets:
    - profitPercentage: 0.02
      quantityPercentage: 0.5
      marginOrderSideEffect: repay

